### PR TITLE
Add functionality

### PR DESCRIPTION
**Pull request by SquirtleSquadLeader**
Okay, so... I am trying increase the functionality of this driver.  I added some resets , low power mode function, and some other stuff.  I wanted to take a pause and see what the maintainers think about this before I continue.  I appreciate any feedback/comments.  I am a novice programmer trying to learn and pitch in.  Thanks!

### CODE REVIEW

**Comment by SquirtleSquadLeader** [comment]
@FoamyGuy  or @ladyada could you offer any advice on next steps to get past errors?  I can't tell if pylint is at fault... or something I did.  I appreciate any help you could provide.

**Comment by SquirtleSquadLeader** [comment]
@caternuson forgot to add you on my pylint advice request

**Comment by ladyada** [comment]
hi there are *a lot* of changes which makes it very hard to review what changed. please submit small, bite-sized PRs that do one thing at a time. it will be easier to review, CI and merge

**Comment by SquirtleSquadLeader** [comment]
> hi there are *a lot* of changes which makes it very hard to review what changed. please submit small, bite-sized PRs that do one thing at a time. it will be easier to review, CI and merge

Understood.  Will do.  I appreciate the patience 🙏.

**Comment by caternuson** [comment]
@SquirtleSquadLeader The pylint fail is weird - it's like pylint itself is crashing. Not that it ran but flagged code as needing changing. Suggest not worrying about it at this point. Focus on making PR smaller as suggested and see what happens when the CI runs on that.

**Comment by SquirtleSquadLeader** [comment]
Okay, I was thinking same.  But I am new to linting.  So I wasn't sure if I had caused that error somehow.  Just trying to prevent repeating it if so.


Will do.  I'll break out tomorrow for one feature and resubmit.  See how that goes. 

Thanks for the help!

**Pull request closed without merging**
