### PR TITLE
Calibration

### PR DESCRIPTION
**Pull request by jan94**
Hi!
I have added a calibration method to the adafruit_circuitpython_mpu6050!
It is based on Melika Barzegarans' code (see: https://github.com/melikabarzegaran/mpu6050-raw-calibration)

I think it would be nice to have this feature, so that the measurements are more accurate :)

Greetings
Jan

### CODE REVIEW

**Comment by jan94** [comment]
@ladyada it looks like there is something wrong with the build pipline...
`reuse....................................................................Passed
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
pylint (library code)....................................................Passed
pylint (examples code)...................................................Passed

Error: Process completed with exit code 1.`

**Comment by ladyada** [comment]
image

https://learn.adafruit.com/improve-your-code-with-pylint

**Comment by jan94** [comment]
Oh sorry, I obviously missed that :/ ...

**Comment by ladyada** [comment]
ok looking! what platform did you test this on, a microcontroller or CPython?

**Comment by jan94** [comment]
CPython (RaspberryPi Zero W)

**Comment by ladyada** [comment]
OK your code uses Typing which will break support for micrcontrollers because it doesnt exist. for that reason, its best to turn the additional code into an example that 'wrappers' the mpu6050 - same code, just as an example sketch!

**Comment by jan94** [comment]
The typing was just added for convenience, I can remove that.

**Comment by ladyada** [comment]
i still really would prefer it as an example, that way we can also use it with other sensors...it doesnt belong in the driver :/

**Comment by jan94** [comment]
The problem with integrating it as an example is, that the calibration needs to have raw values and the library only provides the converted ones. Also there is I2C stuff going on which should be within the lib, I would say.

**Comment by ladyada** [comment]
you dont need or want the raw values, the output from the sensor's accelerometer/gyro are going to be 'shifted' to the scaling. you really want to stick to the scaled values, they're floats so you have the precision you need, ya can just wrapper those `property`s!

**Comment by jan94** [comment]
The sensor internally has some registers that it takes the offset from. To these registers (which are sensor-type-specific) one needs to write the raw values.
Maybe I'm not realizing would you mean... can you provide a short example ?

**Comment by ladyada** [comment]
for this
```
   _raw_accel_offset_x = UnaryStruct(_MPU6050_ACCEL_OFFSET_X, ">h")
    _raw_accel_offset_y = UnaryStruct(_MPU6050_ACCEL_OFFSET_Y, ">h")
    _raw_accel_offset_z = UnaryStruct(_MPU6050_ACCEL_OFFSET_Z, ">h")

    _raw_gyro_offset_x = UnaryStruct(_MPU6050_GYRO_OFFSET_X, ">h")
    _raw_gyro_offset_y = UnaryStruct(_MPU6050_GYRO_OFFSET_Y, ">h")
    _raw_gyro_offset_z = UnaryStruct(_MPU6050_GYRO_OFFSET_Z, ">h")
```
remove the _ prefix, you can just write/read from the object variable, so it does not need a property setter/getter. then just assign those from the example sketch!

**Comment by jan94** [comment]
OK, effectively all the code I added here would be outside the lib, within an example sketch ?

**Comment by jan94** [comment]
That is actually what I wanted to avoid, but I respect that :)

**Comment by ladyada** [comment]
yeah we totally totally understand why... but we also have a lot of incentive to minimize 'user' code within drivers because many circuitpython chips are very low memory :/ its for a good cause! :)

**Comment by tannewt** [comment]
@jan94 Do you have any CircuitPython microcontroller boards? I'm curious if the typed code would load. I'd like to get CP ignoring it so that the libs can have type info. Type info is very helpful for IDEs.

**Pull request closed without merging**
