### PR TITLE
Attempting to execute first PR

### PR DESCRIPTION
**Pull request by SquirtleSquadLeader**
... maybe this is it?

Added functionality to allow the user to create 2 different MPU-6050's with different addresses.  Added some functional checks along the road to creating the object as well.  Looking to start small and learn from this.

### CODE REVIEW

**Comment by FoamyGuy** [comment]
@SquirtleSquadLeader we use pre-commit to run a handful of checks on the code automatically. This page explains how we use it: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code and the next few pages in the same guide talk about the individual components within. The black code formatting and some of the other checks are what are causing the checks not to pass in this case. 

The easiest way to resolve is set up pre-commit locally and run it in this branch and then make a commit with the changes that it will make.

**Comment by SquirtleSquadLeader** [comment]
> @SquirtleSquadLeader we use pre-commit to run a handful of checks on the code automatically. This page explains how we use it: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code and the next few pages in the same guide talk about the individual components within. The black code formatting and some of the other checks are what are causing the checks not to pass in this case. 
> 
> The easiest way to resolve is set up pre-commit locally and run it in this branch and then make a commit with the changes that it will make.

Okay sounds good.  I will try that guide tonight.  I appreciate the guidance, @FoamyGuy . #WarningRookieAtWork

**Comment by SquirtleSquadLeader** [comment]
image
@FoamyGuy @ladyada 

Thank you for the help FoamyGuy! I learned quite a bit.  Look forward to any input (good/bad).

**Comment by ladyada** [comment]
hi this change doesnt make a ton of sense to us - why not just instantiate two MPU6050s in a test example? just pass in two different addresses, its supported

**Comment by caternuson** [comment]
yep. multiple should already be supported, ex:
```python
i2c = board.I2C()  # uses board.SCL and board.SDA
mpu1 = adafruit_mpu6050.MPU6050(i2c)  # uses default address
mpu2 = adafruit_mpu6050.MPU6050(i2c, 0x69)  # specify alt address
```

**Comment by SquirtleSquadLeader** [comment]
If I understood correctly you pass in the I2C Bus.  Then the MPU instantiates using 0x68 (default address).  If you raise Pin AD0 high, the i2c_device object will still be looking for a device address of 0x68. So there exists, I think, a chance that you go no communication if AD0 is high.  

If I am incorrect, my apologies.  And I genuinely appreciate the input.

Sorry for wasting everyone's time.  I'll go back and check the code.

**Comment by SquirtleSquadLeader** [comment]
> yep. multiple should already be supported, ex:
> ```python
> i2c = board.I2C()  # uses board.SCL and board.SDA
> mpu1 = adafruit_mpu6050.MPU6050(i2c)  # uses default address
> mpu2 = adafruit_mpu6050.MPU6050(i2c, 0x69)  # specify alt address
> ```

Understood.  Facepalm.  Thank you!  Always fitting when your first attempt is an abysmal failure.  But I did learn the process.

**Comment by caternuson** [comment]
No worries - you dealt with getting the CI to pass. That's a very worthwhile experience builder if you are planning on making PR's in the future. Dealing with the CI stuff can be a confusing and annoying road block when new to it.

**Comment by SquirtleSquadLeader** [comment]
> hi this change doesnt make a ton of sense to us - why not just instantiate two MPU6050s in a test example? just pass in two different addresses, its supported

@ladyada 

My apologies.  I had it conflict with my RTC DS3231 and I didn't understand the implementation as it was already written.    So I rewrote it,  not knowing the functionality was already there.  I did add a check on the address and employ a confirmation with a register call.  Not super flashy.  

I have more functionality in use but I just wanted to start small.  I have a good bit of the register map exposed via CP Registers library.  I'll try another PR with some features that aren't already there :facepalm: .

**Comment by ladyada** [comment]
its all good, you're learning a LOT and getting good experience! :)

**Pull request closed without merging**
